base_set_cards = {
    1: "Alakazam",
    2: "Blastoise",
    3: "Chansey",
    4: "Charizard",
    5: "Clefairy",
    6: "Gyarados",
    7: "Hitmonchan",
    8: "Machamp",
    9: "Magneton",
    10: "Mewtwo",
    11: "Nidoking",
    12: "Ninetales",
    13: "Poliwrath",
    14: "Raichu",
    15: "Venusaur",
    16: "Zapdos",
    17: "Beedrill",
    18: "Dragonair",
    19: "Dugtrio",
    20: "Electabuzz",
    21: "Electrode",
    22: "Pidgeotto",
    23: "Arcanine",
    24: "Charmeleon",
    25: "Dewgong",
    26: "Dratini",
    27: "Farfetch'd",
    28: "Growlithe",
    29: "Haunter",
    30: "Ivysaur",
    31: "Jynx",
    32: "Kadabra",
    33: "Kakuna",
    34: "Machoke",
    35: "Magikarp",
    36: "Magmar",
    37: "Nidorino",
    38: "Poliwhirl",
    39: "Porygon",
    40: "Raticate",
    41: "Seel",
    42: "Wartortle",
    43: "Abra",
    44: "Bulbasaur",
    45: "Caterpie",
    46: "Charmander",
    47: "Diglett",
    48: "Doduo",
    49: "Drowzee",
    50: "Gastly",
    51: "Koffing",
    52: "Machop",
    53: "Magnemite",
    54: "Metapod",
    55: "Nidoran♀",
    56: "Onix",
    57: "Pidgey",
    58: "Pikachu",
    59: "Poliwag",
    60: "Ponyta",
    61: "Rattata",
    62: "Sandshrew",
    63: "Squirtle",
    64: "Starmie",
    65: "Staryu",
    66: "Tangela",
    67: "Voltorb",
    68: "Vulpix",
    69: "Weedle",
    70: "Clefairy Doll",
    71: "Computer Search",
    72: "Devolution Spray",
    73: "Imposter Professor Oak",
    74: "Item Finder",
    75: "Lass",
    76: "Pokémon Breeder",
    77: "Pokémon Trader",
    78: "Scoop Up",
    79: "Super Energy Removal",
    80: "Defender",
    81: "Energy Retrieval",
    82: "Full Heal",
    83: "Maintenance",
    84: "PlusPower",
    85: "Pokémon Center",
    86: "Pokémon Flute",
    87: "Pokédex",
    88: "Professor Oak",
    89: "Revive",
    90: "Super Potion",
    91: "Bill",
    92: "Energy Removal",
    93: "Gust of Wind",
    94: "Potion",
    95: "Switch",
    96: "Double Colorless Energy",
    97: "Fighting Energy",
    98: "Fire Energy",
    99: "Grass Energy",
    100: "Lightning Energy",
    101: "Psychic Energy",
    102: "Water Energy"
}